# Generated by Django 3.2.7 on 2021-10-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0026_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Japan', 'Japan'), ('China', 'China'), ('Usa', 'Usa'), ('Russia', 'Russia'), ('Great Britain', 'Great Britain'), ('Australia', 'Australia'), ('Malaysia', 'Malaysia'), ('Canada', 'Canada'), ('Egypt', 'Egypt'), ('Scotland', 'Scotland'), ('Brazil', 'Brazil'), ('France', 'France'), ('Argentina', 'Argentina'), ('Sweden', 'Sweden'), ('South korea', 'South korea'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('New Zealand', 'New Zealand'), ('Germany', 'Germany'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Croatia', 'Croatia'), ('Switzerland', 'Switzerland'), ('Mexico', 'Mexico'), ('Belgium', 'Belgium'), ('Turkey', 'Turkey'), ('Qatar', 'Qatar'), ('South Africa', 'South Africa'), ('Jamaica', 'Jamaica'), ('Colombia', 'Colombia'), ('Peru', 'Peru'), ('ukraine', 'ukraine')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='sport',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Hockey', 'Hockey'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Boxing', 'Boxing'), ('Diving', 'Diving'), ('Handball', 'Handball'), ('Swimming', 'Swimming'), ('Shooting', 'Shooting'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Weight Lifting', 'Weight Lifting'), ('Archery', 'Archery'), ('Javelin', 'Javelin'), ('Golf', 'Golf'), ('Table Tennis', 'Table Tennis'), ('Football', 'Football'), ('Wrestling', 'Wrestling'), ('Beach Volleyball', 'Beach Volleyball'), ('Karate', 'Karate'), ('Judo', 'Judo'), ('Athletics', 'Athletics'), ('Water Polo', 'Water Polo'), ('Track Cycling', 'Track Cycling'), ('Road Cycling', 'Road Cycling'), ('Rowing', 'Rowing'), ('Rugby', 'Rugby'), ('Sailing', 'Sailing'), ('Skate Boarding', 'Skate Boarding'), ('Surfing', 'Surfing')], max_length=32),
        ),
    ]
